### ISSUE TITLE
feat: change supagen model brick

### ISSUE THREAD

**Issue by andikadeveloper** [supagen/supagen#25]
## Problem

For now, we have created our own model brick to generate model class from supabase tables. I just do some research and I found that there is already model brick created by other developer and it has more complete features.

## Solution

Change the model brick to this https://brickhub.dev/bricks/model/0.9.1 and I think we should make a new component call `converter` (ex: `DartConverter`) to handle convert postgres data types into programming language data types (for now let's support dart only)

## Involment
**If the feature request is approved, would you be willing to submit a PR?**

- [ ] Yes
- [x] No (I want other contribute to this)

## Implementation Plan (If you want to get involved)

- [ ] Change model brick in `DartModelGenerator`
- [ ] Create new component `converter` and call it when convert postgres data types

**Comment by Sarveshk76** [comment]
I would like to work on this issue

**Comment by andikadeveloper** [comment]
Okay @Sarveshk76, I just assigned this issue to you, and we are excited to wait for the PR for this issue.

**Comment by Sarveshk76** [comment]
![image](https://github.com/user-attachments/assets/53a612f5-a771-4477-ac3a-2d138c22a4a6)
Can you help me with this?

**Comment by andikadeveloper** [comment]
@Sarveshk76 Could you send a screenshot with verbose output? Just add a `--verbose` flag after `init` command.

**Comment by Sarveshk76** [comment]
![image](https://github.com/user-attachments/assets/5fec489c-fca3-4abb-b56b-3a3cf0a5b9cf)

**Comment by andikadeveloper** [comment]
@Sarveshk76 It looks like, it's only happen in Windows and the error related to `mason` issue.
![image](https://github.com/user-attachments/assets/7d64336e-9136-4073-bf4c-79abd6f7071a)

You can fix it by adding this into your environment variable. See mason issue for the detail:
https://github.com/felangel/mason/issues/496#issuecomment-1494293205

**Comment by andikadeveloper** [comment]
Hey @Sarveshk76, any update about this issue?
