### ISSUE TITLE
feat: create a script to automate installation of supagen CLI into Windows OS

### ISSUE THREAD

**Issue by andikadeveloper** [supagen/supagen#27]
## Problem

For now, there is no script for install `supagen` CLI into Windows OS.
We have to download, extract, and configure it manually.

## Solution

Create a script to automate installation of `supagen` CLI into Windows OS.
For an example you can see linux installation script that already there: https://github.com/supagen/supagen/blob/main/scripts/install.sh

For an example related to Windows script, you can see in this repo:
https://github.com/leoafarias/fvm/blob/main/scripts/install.ps1

## Involment
**If the feature request is approved, would you be willing to submit a PR?**

- [ ] Yes
- [x] No (I want other contribute to this)

## Implementation Plan (If you want to get involved)

- [x] Create installation script for windows in the folder:
https://github.com/supagen/supagen/tree/main/scripts
- [x] Test the script already running properly, with attach some evidence into your pull request

**Comment by Prakharpan-dey** [comment]
@andikadeveloper Hey i made a script for this . 
For running the script you need to open powershell in admin mode then go to directory where the script is stored and then run the script . I have attached a video proof for that . If it looks right assign me this issue and i will raise a PR for it

Uploading 2024-10-08 16-10-20.mp4…

**Comment by Prakharpan-dey** [comment]
Hey i i would love to work on this issue
