### ISSUE TITLE
feat: add ability to generate C4

### ISSUE THREAD

**Issue by andikadeveloper** [supagen/supagen#30]
## Problem

Too much effort to initate c4 boilerplate

## Solution

We need to automate c4 boilerplate creation with supagen generate

## Involment
**If the feature request is approved, would you be willing to submit a PR?**

- [x] Yes
- [ ] No (I want other contribute to this)

## Implementation Plan (If you want to get involved)

- [x] Create new mason brick with name c4 in `supagen_bricks` repo and test the results
- [x] Create new command `supagen generate` with option `c4`
- [x] Create new generator to call c4 brick
- [x] Testing the result
